added .status.observedGeneration to camel K CRDs
apache/camel-k pull request #3218
Opened 2022-04-17 18:46 UTC by SubhasmitaSw

fixes: issue #3182 

cc @astefanutti

2022-04-18 05:50 UTC, tadayosi approved these changes

2022-04-18 09:12 UTC, squakez reviewed
Nice, thanks. However I think we're still missing the update part. We should check in the reconciliation cycle and update accordingly.

2022-04-18 09:12 UTC, squakez commented
We should also provide some basic E2E test if possible.

2022-04-18 10:05 UTC, SubhasmitaSw commented
> Nice, thanks. However I think we're still missing the update part. We should check in the reconciliation cycle and update accordingly.

For this part, @astefanutti was about to share some background references to me regarding `metadata.generation` field, however he seems to be occupied so I'll be glad if you could provide some information on proceeding with this.

2022-04-18 10:22 UTC, squakez commented
I am not very familiar with this part, but I think you can have a look at the update function, which should be in charge to set that value: https://github.com/apache/camel-k/blob/main/pkg/controller/build/build_controller.go#L74

2022-04-20 07:43 UTC, astefanutti requested changes

2022-04-20 07:43 UTC, astefanutti commented on pkg/controller/kamelet/kamelet_controller.go
> +	target.Status.ObservedGeneration = instance.GetGeneration()
This must be added just before:

```
if err := r.client.Status().Patch(ctx, target, ctrl.MergeFrom(&instance)); err != nil {
```

Line 181.

2022-04-20 07:43 UTC, astefanutti commented on pkg/controller/kameletbinding/kamelet_binding_controller.go
> +	target.Status.ObservedGeneration = instance.Generation
This must be added just before line 195.

2022-04-20 07:43 UTC, astefanutti commented on pkg/controller/integrationplatform/integrationplatform_controller.go
> +	target.Status.ObservedGeneration = instance.Generation
I'd recommend to add it just before line 195.

2022-04-20 07:43 UTC, astefanutti commented on pkg/controller/integrationkit/integrationkit_controller.go
> +	target.Status.ObservedGeneration = base.Generation
This is better moved after line 311.

2022-04-20 07:43 UTC, astefanutti commented on pkg/controller/integration/integration_controller.go
> +	target.Status.ObservedGeneration = base.Generation
I'd suggest to move it after line 347.

2022-04-20 07:43 UTC, astefanutti commented on pkg/apis/camel/v1alpha1/kamelet_binding_types.go
> +	// ObservedGeneration is the generation observed by the KameletBinding controller.
```suggestion
	// ObservedGeneration is the most recent generation observed for this KameletBinding.
```

2022-04-20 07:43 UTC, astefanutti commented on pkg/apis/camel/v1/integrationplatform_types.go
> +	// ObservedGeneration is the most recent generation observed by the controller. It corresponds to the controller's `metadata.generation` and is updated on mutation by the API Server.
```suggestion
	// ObservedGeneration is the most recent generation observed for this IntegrationPlatform.
```

2022-04-20 07:43 UTC, astefanutti commented on pkg/apis/camel/v1/integrationkit_types.go
> +	// ObservedGeneration is the last generation change we observed. This is used to determine if we need to refresh the status of the integration kit.
```suggestion
	// ObservedGeneration is the most recent generation observed for this IntegrationKit.
```

2022-04-20 07:43 UTC, astefanutti commented on pkg/apis/camel/v1/integration_types.go
> +	// ObservedGeneration is the most recent generation observed for this Integration.
```suggestion
	// ObservedGeneration is the most recent generation observed for this Integration.
```

2022-04-20 07:43 UTC, astefanutti commented on pkg/apis/camel/v1/build_types.go
> +	//ObservedGeneration is the most recent generation observed for this Build.
```suggestion
	// ObservedGeneration is the most recent generation observed for this Build.
```

2022-04-20 08:59 UTC, astefanutti reviewed
Added a couple of comments, also please regenerate the CRDs and we should be good to go :)

2022-04-20 08:59 UTC, astefanutti commented on pkg/controller/kamelet/kamelet_controller.go
> +			// Update the metadata.generation to avoid conflicts with other reconcile operations.
That comment can be removed.

2022-04-20 08:59 UTC, astefanutti commented on pkg/controller/kameletbinding/kamelet_binding_controller.go
> +				// Update the metadata.Generation to avoid conflicts with other clients updating the resource at the same time we are reconciling it.
That comment can be removed.

2022-04-20 08:59 UTC, astefanutti commented on pkg/controller/integrationplatform/integrationplatform_controller.go
> +				// Update the metadata.generation to avoid conflicts with other reconcile operations
That comment can be removed.

2022-04-20 10:07 UTC, astefanutti commented on pkg/apis/camel/v1/integration_types.go
> +	// It corresponds to the Integration's generation, which is updated on mutation by the API Server.
That line can be removed.

2022-04-20 18:37 UTC, astefanutti approved these changes
Thanks!

2022-04-21 07:25 UTC, astefanutti commented
There are some YAKS tests failing, that requires a change in YAKS itself. I've created citrusframework/yaks#403. Once it's fixed, that PR can be merged.

2022-04-21 09:26 UTC, christophd commented
YAKS has a pinned prerelease available [0.11.0-202204210858](https://github.com/citrusframework/yaks/releases/tag/0.11.0-202204210858) that should fix the issue.

@SubhasmitaSw to use the fixed YAKS version please update the version in the GitHub actions workflow to `0.11.0-202204210858`:
https://github.com/apache/camel-k/blob/main/.github/actions/e2e-knative-yaks/action.yml#L81

2022-06-03 14:10 UTC, astefanutti commented
Let's merge this. The `TestKitTimerToLogFullNativeBuild` test failure is already present in main branch.

2022-06-03 14:10 UTC, merged

2022-06-03 14:10 UTC, astefanutti commented
Thanks!