Fix windows paths in --resource
apache/camel-k pull request #3484
Opened 2022-07-26 08:24 UTC by mmajerni

**Release Note**
```release-note
NONE
```

2022-07-26 08:25 UTC, oscerd approved these changes

2022-07-26 08:49 UTC, squakez approved these changes
LGTM. We better backport also on `main` branch.

2022-07-27 07:25 UTC, tadayosi requested changes
Same change request as PR for main.

2022-07-27 14:23 UTC, mmajerni commented
Changed to `filepath.ToSlash()`

2022-07-27 22:56 UTC, tadayosi approved these changes

2022-07-28 00:57 UTC, merged