Add GH Issue Template
apache/camel-k pull request #4689
Opened 2023-08-23 20:24 UTC by anishrajan25

Fixes Issue #4675

2023-08-23 20:25 UTC, anishrajan25 commented
@claudio4j Could you please review the PR?

2023-08-23 21:01 UTC, claudio4j requested changes
Hey Anish, this template looks very good, I just requested some minor changes.
Thank you for the contribution.

2023-08-23 21:01 UTC, claudio4j commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +      description: Which version of the Camel K are you running?
Add something like "Verify if the kamel cli is the same version as the camel-k-operator with: kamel version -a"

2023-08-24 05:39 UTC, anishrajan25 commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +        Please indicate from which component the logs originate.
Sure, I have added additional pointers to add these helper points

2023-08-24 05:56 UTC, anishrajan25 commented
Here are the screenshots for reference as to how the templates would look once rendered:
### Issues Page
<img width="1284" alt="image" src="https://github.com/apache/camel-k/assets/56666741/6f3e8d7b-88cb-48fc-870a-d3e964ee9a0a">

---

### Bug Report Page
![image](https://github.com/apache/camel-k/assets/56666741/f5bc467b-cbb5-4c3f-b78a-31bab813480f)

---

### Feature Request Page
![image](https://github.com/apache/camel-k/assets/56666741/4a6923f3-d506-4c86-879d-eaa9fdbdb828)

2023-08-24 06:50 UTC, squakez reviewed
IMO there's too much information required for any issue. If we want to collect information it would be enough to provide some text form with the version, the log and a free from with the description. My concern is that we are adding a barrier for anybody willing to submit a feedback. 

It also is making references to CNCF instead of Apache foundation.

For me it's a -1, but if the rest of the community is okey with it, at least, let's make it simpler.

cc @oscerd @lburgazzoli @gansheer @christophd

2023-08-24 23:16 UTC, claudio4j commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +        - Please be respectful and considerate of others (see [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)).
Can you this link for the code of conduct 
https://www.apache.org/foundation/policies/conduct

2023-08-24 23:26 UTC, claudio4j commented
Well, let's try to reduce some extra fields, Anish wdyt to have only one textarea field for the following subjects ?
What happened?
Steps to reproduce
Expected behavior

And I think we can drop these fields
Screenshot
Additional context
Language
Operating system

It's going to be good for a first iteration of this form.

2023-08-25 06:44 UTC, christophd commented
In my experience people ignore the given fields most of the time. But I like the pointers to zulip chat and mailing list as part of the landing page for new issues. This may direct people to a better suited discussion forum for their individual question.

Also +1 to combining at least `What happened?` and `Expected behavior` fields into one single question. In my experience people describe the whole scenario in `What happened?` section and then write the exact same statement in slightly other wording to the `Expected behavior` field (like What happended? "This and that did not work properly for me", Expected behavior: "This and that should work properly")

2023-08-25 10:51 UTC, anishrajan25 commented
@claudio4j I am aligned on dropping the following fields:
- Screenshot
- Additional context
- Language
- Operating system

Also as @christophd suggested, it would be good to merge `What happened?` and `Expected behavior` fields into one.

But I would suggested to have the `Steps to Reproduce` and `Relevant log output` as separate fields in addition to the `What happened?` because:
- As per my experience (and I'm a beginner when it comes to Open Source), at times the issues don't have much information and it gets hard for someone who is fairly new to the project to understand what exactly is the issue.
- Having  `Steps to Reproduce` and `Relevant log output` would definitely help in providing additional information to folks who want to contribute.
- Also having the field for `Camel-K version` would also be a helpful thing.
- I understand these fields might act as a barrier in some cases, so we can mark the fields other than `What happened?` as optional.

2023-08-25 12:44 UTC, claudio4j commented
Sounds good Anish, my understanding is is already good for a first try, I will approve it and we can get back to it later if it requires changes to allow a more friendly page.
Thank you Anish.

2023-08-25 14:01 UTC, anishrajan25 commented
I have updated the PR as discussed. @claudio4j You can have a final look.

This is how the Bug Report Form would look like now:
![image](https://github.com/apache/camel-k/assets/56666741/8f1a5d76-0522-4e5a-9de9-cadb164e76a9)

2023-08-25 15:04 UTC, claudio4j approved these changes

2023-08-25 17:23 UTC, merged