Fix semantic version check of camel-k-runtime
apache/camel-k pull request #4731
Opened 2023-09-12 04:02 UTC by claudio4j

Fix https://github.com/apache/camel-k/issues/4715

* Upgrade semver api to v3
* `kamel version -a` relies on loading the catalog using the runtime provider, which is not set in the IntegrationPlatform object, so rendering null and not loading the CamelCatalog object.
* It may occur the CamelCatalog object is not in the same namespace of the camel-k-operator pod, so we should not print an error message in case the CamelCatalog is not found.
* In the catalog initialization, print any error related to building the container image in the camel-k-operator log as the error was set only in the CamelCatalog status object.
* Change the `RuntimeVersion` type of CamelCatalog object to string, as there may be cases of the runtime version not following the semantic version.
* The `findBestMatch` was renamed to `findCatalog`, since it was not actually trying to match a version rule, but plainly using a full version to check it.

**Release Note**
```release-note
Update semver golang api to v3
```

2023-09-12 04:13 UTC, oscerd approved these changes

2023-09-12 09:19 UTC, squakez requested changes
With this PR we are removing at all the semver logic. The `findBestMatch` was used when you want to use a catalog which is not exactly known. For instance, running: `kamel run test.yaml -t camel.runtime-version=3.x` will get the latest 3.x catalog. This is particularly interesting now that we are independent from the runtime. However, we should include this feature in the doc and have an E2E test as well.

2023-09-12 09:19 UTC, squakez commented on pkg/controller/catalog/initialize.go
> +		Log.Error(err, "Error trying to build Camel K builder container")
We are returning the error. The caller should know what to do with it, if printing a warning or what else.

2023-09-13 22:29 UTC, claudio4j commented
Closing this in favor of https://github.com/apache/camel-k/pull/4741

2023-09-13 22:29 UTC, closed without merging