[java] Add sundrio to generate builders
apache/camel-k pull request #4931
Opened 2023-11-27 15:06 UTC by andreaTP

Add `sundrio` to generate builder pattern for the model classes of the generated CRD.

With the upcoming version of `kubernetes-client-bom-with-deps` we should be able to remove the explicit versions of `sundrio` and `lombok` too.

2023-11-27 15:38 UTC, squakez requested changes
We need to decline this one. We already discussed with the community the opportunity to use code generators such as Lombok. With a negative answer.

2023-11-27 15:42 UTC, claudio4j commented
@andreaTP what would be the use case to manipulate Camel K k8s objects ?

2023-11-28 07:10 UTC, squakez commented
Okey. Maybe, given that this is an auto generated project where user is not meant to manually compile it, we can accept it. @oscerd wdyt?

2023-11-28 08:17 UTC, oscerd approved these changes
I hope we can remove lombok even if it's only a runtime dependency.

2023-11-28 08:54 UTC, merged

2023-11-28 08:55 UTC, squakez commented
@andreaTP please, remind to remove the dependencies in the future when no longer necessary. Thanks!

2023-11-28 09:53 UTC, andreaTP commented
@oscerd and @squakez I'm not sure about those last comments, both `lombok` and `sundrio` are marked as "provided".

This means that they will be available on the classpath only during compilation and they are not going to be considered transitive dependencies of the resulting artifact.

> remove lombok even if it's only a runtime dependency.

It's not a runtime dependency and we can't remove it to get the generated builder pattern.

> remind to remove the dependencies in the future when no longer necessary

Just to be clear, the only thing I will change over the current configuration is the removal of the explicit `sundrio` and `lombok` version and relevant "property".

2023-11-28 09:59 UTC, oscerd commented
Our idea is to avoid Lombok as much as we can. Since this is a separated context for generating stuff, that's fine, but we would like to avoid the spreading of Lombok around the codebase. It's provided and that's fine.

2023-11-28 10:11 UTC, andreaTP commented
agreed